python/nameplate/urls.py
from django.contrib import admin
from django.urls import path

from kiosk.views import outlook_login, get_token, home, outlook_logout, select_room, set_room, room_info, schedule_room

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'login/', outlook_login, name='outlook_login'),
    path(r'logout/', outlook_logout, name='outlook_logout'),
    path(r'get_token/', get_token, name='get_token'),
    path(r'select_room/', select_room, name='select_room'),
    path(r'set_room', set_room, name='set_room'),
    path(r'room_info', room_info, name='room_info'),
    path(r'schedule_room', schedule_room, name='schedule_room'),
    path(r'', home, name='home')
]

python/kiosk/models.py
from django.db import models

# Create your models here.

python/kiosk/forms.py
from django import forms
from kiosk.outlook_service import datetime_format


class SetRoomForm(forms.Form):
    room_email = forms.CharField(widget = forms.HiddenInput())


class ScheduleRoomForm(forms.Form):
    start_time = forms.DateTimeField(widget = forms.HiddenInput(), input_formats=[datetime_format])
    duration_minutes = forms.IntegerField(widget = forms.HiddenInput())
    room_email = forms.CharField(widget = forms.HiddenInput())

python/kiosk/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponseBadRequest, HttpResponseNotFound, JsonResponse
import kiosk.auth_helper
import kiosk.outlook_service
import kiosk.availability_finder
from datetime import datetime
from django.contrib import messages
from kiosk.forms import SetRoomForm, ScheduleRoomForm


def require_login(view):
    def function_wrapper(request):
        token = kiosk.auth_helper.get_access_token(request, request.build_absolute_uri(reverse('get_token')))
        if token:
            return view(request, token)
        else:
            return HttpResponseRedirect(reverse('outlook_login'))
    return function_wrapper


@csrf_protect
@require_login
def schedule_room(request, access_token):
    if request.method == "POST":
        schedule = ScheduleRoomForm(request.POST)
        if not schedule.is_valid():
            return HttpResponseBadRequest("room_email is required.")
        if kiosk.outlook_service.schedule_room(
            access_token,
            schedule.cleaned_data['room_email'],
            schedule.cleaned_data['start_time'],
            schedule.cleaned_data['duration_minutes']
        ):
            messages.success(request, "Successfully Scheduled Room")
        else:
            messages.error(request, "Unable to Schedule Room")
        return HttpResponseRedirect(reverse("home"))
    return HttpResponseRedirect(reverse("home"))


@require_login
def room_info(request, access_token):
    room_email = request.GET.get('room_email')
    if room_email is None:
        return HttpResponseBadRequest("room_email is required.")
    availability = kiosk.availability_finder.get_upcoming_availability(access_token, room_email, datetime.now())
    user = kiosk.outlook_service.get_user(access_token, room_email)
    if availability is not None and user is not None:
        return JsonResponse({
            "name": user['displayName'],
            "availability": availability
        })
    else:
        return HttpResponseBadRequest("Invalid room_email")


@csrf_protect
@require_login
def set_room(request, access_token):
    if request.method == "POST":
        room = SetRoomForm(request.POST)
        if not room.is_valid():
            return HttpResponseBadRequest("room_email is required.")
        if kiosk.outlook_service.set_room(request.session, access_token, room.cleaned_data['room_email']):
            return HttpResponseRedirect(reverse("home"))
        else:
            return HttpResponseBadRequest("Invalid room_email")
    return HttpResponseRedirect(reverse("home"))


@require_login
def home(request, access_token):
    room_email = request.session.get('room_email')
    user = None
    if room_email:
        user = kiosk.outlook_service.get_user(access_token, room_email)
        display_name = user.get('displayName')
    if not user or not display_name:
        return HttpResponseRedirect(reverse("select_room"))
    context = {
        'display_name': display_name,
        'room_email': room_email,
        'schedule_room_form': ScheduleRoomForm(data={'room_email': room_email})
    }
    return render(request, "kiosk/welcome.html", context)


@require_login
def select_room(request, access_token):
    rooms = kiosk.outlook_service.get_rooms(access_token)
    if rooms is None:
        return HttpResponseNotFound("Could not get the list of rooms.")
    context = {'rooms': []}
    for room in rooms:
        context['rooms'] += [{
            'form': SetRoomForm(data={'room_email': room['address']}),
            'name': room['name']
        }]
    return render(request, "kiosk/select_room.html", context)


def outlook_logout(request):
    request.session.clear()
    return HttpResponseRedirect(reverse('outlook_login'))


def outlook_login(request):
    redirect_uri = request.build_absolute_uri(reverse('get_token'))
    signin_url = kiosk.auth_helper.get_signin_url(redirect_uri)
    context = {'signin_url': signin_url}

    token = kiosk.auth_helper.get_access_token(request, request.build_absolute_uri(reverse('get_token')))
    if token:
        context['logged_in'] = True
        context['user_email'] = kiosk.outlook_service.get_me(token)['mail']
        context['logout_link'] = reverse("outlook_logout")
    else:
        context['logged_in'] = False
    return render(request, "kiosk/outlook_login.html", context)


def get_token(request):
    auth_code = request.GET.get('code')
    request.session.clear()
    if kiosk.auth_helper.process_auth_code(request, auth_code, request.build_absolute_uri(reverse('get_token'))):
        return HttpResponseRedirect(reverse('home'))
    else:
        return HttpResponseBadRequest("Code did not generate a valid access token.")

python/kiosk/templates/kiosk/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Nameplate Kiosk</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/kiosk.css' %}">
</head>
<body style="padding-top: 70px; padding-bottom: 70px;">

    <script src="{% static 'js/jquery.js' %}"></script>

    <div class="container main-container jumbotron">
        <div id="message" {% if message_color %}color="{{ message_color }}"{% endif %} align="center">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        </div>
        {% block content %}{% endblock %}
    </div>

    <script>

        function fadeout_message() {
            $("#message").fadeOut(1000);
        }

        setTimeout(fadeout_message, 15000);
    </script>
</body>
</html>

python/kiosk/templates/kiosk/outlook_login.html
{% extends "kiosk/layout.html" %}
{% block content %}
    <div class="jumbotron">
        <h1>Python Outlook Sample</h1>

        {% if logged_in %}
            Logged in as: {{ user_email }} <br>
            <a class="btn btn-lg btn-primary" href="{{ logout_link }}" role="button" id="connect-button">Logout</a>
        {% else %}
            Not logged in.
        {% endif %}
        <p>
            <a class="btn btn-lg btn-primary" href="{{ signin_url }}" role="button" id="connect-button">Connect to Outlook</a>
        </p>
    </div>
{% endblock %}

python/kiosk/templates/kiosk/select_room.html
{% extends "kiosk/layout.html" %}
{% block content %}
    <div class="jumbotron">
        <h2>Select Room</h2>

        {% for room in rooms %}
            <form action="{% url 'set_room'  %}" method="post">
                {% csrf_token %}
                {{ room.form }}
                <button class="btn btn-lg btn-primary" type="submit">{{ room.name }}</button>
            </form><br>
        {% endfor %}

    </div>
{% endblock %}

python/kiosk/templates/kiosk/welcome.html
{% extends "kiosk/layout.html" %}
{% block content %}
    <div align="center">

        <h1 id="room_name">{{ display_name }}</h1>
        <div id="current_status"></div>
        <div id="upcoming_status"></div>

        <div id="schedule_buttons" hidden>
            <h5>Schedule Meeting For:</h5>
            <a class="btn btn-lg btn-primary" onclick="schedule_for_interval(30)" role="button" id="schedule_button1">30 minutes</a>
            <a class="btn btn-lg btn-primary" onclick="schedule_for_interval(60)" role="button" id="schedule_button2">60 minutes</a>
            <a class="btn btn-lg btn-primary" onclick="schedule_for_interval(90)" role="button" id="schedule_button3">90 minutes</a>
        </div>

    </div>

    <form id="schedule_room_form" method="post" action="{% url 'schedule_room' %}" hidden>
        {% csrf_token %}
        {{ schedule_room_form }}
    </form>

    <script>
        var room_email = "{{ room_email }}";
        var room_info_url = "{% url 'room_info' %}?room_email=" + room_email;
        var start_time = null;
        var start_time_string = null;

        function string_to_date( time ) {
            return Date.parse(time);
        }

        function set_current_status( status ) {
            if (status) {
                document.getElementById("current_status").style.color = 'green';
                document.getElementById("current_status").innerHTML = "Available";
            }
            else {
                document.getElementById("current_status").style.color = 'red';
                document.getElementById("current_status").innerHTML = "Occupied";
            }
        }

        function time_delta_minutes(end_time, start_time) {
            return Math.round((end_time - start_time) / (1000 * 60));
        }

        function set_upcoming_status( availability, offset_minutes) {
                var current_status = availability['0'];
                var state_change_minutes = null;
                if (current_status != availability['30']) {
                    state_change_minutes = 30 - offset_minutes;
                }
                else if (current_status != availability['60']) {
                    state_change_minutes = 60 - offset_minutes;
                }
                else if (current_status != availability['90']) {
                    state_change_minutes = 90 - offset_minutes;
                }
                var new_string = "";
                if ( state_change_minutes != null ) {
                    if ( current_status ) {
                        new_string = "Free for ";
                    }
                    else {
                        new_string = "Free in ";
                    }
                    state_change_minutes = Math.max(1, state_change_minutes);
                    new_string += state_change_minutes + " minute";
                    if ( state_change_minutes != 1 ) {
                        new_string += "s";
                    }
                }
                document.getElementById("upcoming_status").innerHTML = new_string;
        }

        function set_schedule_buttons(availability, current_status, offset_minutes) {
            if ( !current_status ) {
                $("#schedule_buttons").hide();
            }
            else {
                if ( availability['0'] ) {
                    if (offset_minutes <= 25) {
                        $("#schedule_button1").text((30 - offset_minutes) + " minutes");
                        $("#schedule_button1").show();
                    }
                    else
                    {
                        $("#schedule_button1").hide();
                    }
                    if ( availability['30'] ) {
                        $("#schedule_button2").text((60 - offset_minutes) + " minutes");
                        if ( availability['60'] ) {
                            $("#schedule_button3").text((90 - offset_minutes) + " minutes");
                        }
                        else {
                            $("#schedule_button3").hide();
                        }
                    }
                    else {
                        $("#schedule_button2").hide();
                    }
                }
                else {
                    $("#schedule_button1").hide();
                    $("#schedule_button2").hide();
                    $("#schedule_button3").hide();
                }
                $("#schedule_buttons").show();
            }
        }

        function schedule_for_interval( interval_minutes ) {
            if ( start_time_string == null) {
                alert("Error");
            }
            else {
                $("#id_start_time").val(start_time_string);
                $("#id_duration_minutes").val(interval_minutes);
                $("#schedule_room_form").submit();
            }
        }

        function update() {
            $.getJSON( room_info_url, function ( data ) {

                var current_status = data['availability']['0'];
                start_time_string = data['availability']['start_time'];
                start_time = string_to_date(start_time_string);
                var current_time = string_to_date(data['availability']['current_time']);
                var offset_minutes = time_delta_minutes(current_time, start_time);

                set_current_status(current_status);
                set_upcoming_status(data['availability'], offset_minutes);
                set_schedule_buttons(data['availability'], current_status, offset_minutes);
            });
        }
        {% if not messages %}
        update();
        {% endif %}
        setInterval(update, 15000);
    </script>
{% endblock %}